apiVersion: vra.terasky.com/v1alpha1
kind: AWSCloudAccount
metadata:
  annotations:
    meta.upbound.io/example-id: vra/v1alpha1/awscloudaccount
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    accessKey: ${var.access_key}
    description: terraform test cloud account aws
    name: tf-vra-cloud-account-aws
    regions:
    - us-east-1
    - us-west-1
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - key: foo
      value: bar
