apiVersion: vra.terasky.com/v1alpha1
kind: CatalogSourceBlueprint
metadata:
  annotations:
    meta.upbound.io/example-id: vra/v1alpha1/catalogsourceblueprint
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    name: ${var.catalog_source_name}
    projectId: ${var.vra_project_id}
