apiVersion: vra.terasky.com/v1alpha1
kind: ImageProfile
metadata:
  annotations:
    meta.upbound.io/example-id: vra/v1alpha1/imageprofile
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: test image profile
    imageMapping:
    - constraints:
      - expression: '!env:Test'
        mandatory: true
      - expression: foo:bar
        mandatory: false
      imageId: ${data.vra_image.centos.id}
      name: centos
    - cloudConfig: runcmd echo 'Hello'
      imageId: ${data.vra_image.photon.id}
      name: photon
    name: vra-image-profile
    regionId: ${data.vra_region.this.id}
