apiVersion: vra.terasky.com/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: vra/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    customProperties:
      edgeClusterRouterStateLink: /resources/routers/<uuid>
      tier0LogicalRouterStateLink: /resources/routers/<uuid>
    description: My Load Balancer
    name: my-load-balancer
    nics:
    - networkId: ${data.vra_network.my-network.id}
    projectId: ${vra_project.my-project.id}
    routes:
    - healthCheckConfiguration:
      - healthyThreshold: 10
        intervalSeconds: 30
        port: "80"
        protocol: TCP
        timeoutSeconds: 10
        unhealthyThreshold: 2
      memberPort: "80"
      memberProtocol: TCP
      port: "80"
      protocol: TCP
    targets:
    - machineId: ${vra_machine.my_machine.id}
