apiVersion: vra.terasky.com/v1alpha1
kind: NSXTCloudAccount
metadata:
  annotations:
    meta.upbound.io/example-id: vra/v1alpha1/nsxtcloudaccount
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    acceptSelfSignedCert: true
    dcId: ${var.vra_data_collector_id}
    description: foobar
    hostname: ${var.hostname}
    name: tf-nsx-t-account
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - key: foo
      value: bar
    username: ${var.username}
