// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GCPCloudAccountInitParameters struct {

	// GCP Client email.
	// GCP Client email.
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of GCP cloud account.
	// The name of this resource instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// GCP Private key ID.
	// GCP Private key ID.
	PrivateKeyID *string `json:"privateKeyId,omitempty" tf:"private_key_id,omitempty"`

	// GCP Private key.
	// GCP Private key.
	PrivateKeySecretRef v1.SecretKeySelector `json:"privateKeySecretRef" tf:"-"`

	// GCP Project ID.
	// GCP Project ID.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of region names enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// Set of tag keys and values to apply to the cloud account. Example: [ { "key" : "vmware", "value": "provider" } ]
	Tags []GCPCloudAccountTagsInitParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GCPCloudAccountLinksInitParameters struct {
}

type GCPCloudAccountLinksObservation struct {
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// +listType=set
	Hrefs []*string `json:"hrefs,omitempty" tf:"hrefs,omitempty"`

	Rel *string `json:"rel,omitempty" tf:"rel,omitempty"`
}

type GCPCloudAccountLinksParameters struct {
}

type GCPCloudAccountObservation struct {

	// GCP Client email.
	// GCP Client email.
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Date when entity was created. Date and time format is ISO 8601 and UTC.
	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of GCP cloud account.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Hypermedia as the Engine of Application State (HATEOAS) of entity.
	Links []GCPCloudAccountLinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// Name of GCP cloud account.
	// The name of this resource instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of organization that entity belongs to.
	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Email of entity owner.
	// Email of the user that owns the entity.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// GCP Private key ID.
	// GCP Private key ID.
	PrivateKeyID *string `json:"privateKeyId,omitempty" tf:"private_key_id,omitempty"`

	// GCP Project ID.
	// GCP Project ID.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of region names enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// Set of tag keys and values to apply to the cloud account. Example: [ { "key" : "vmware", "value": "provider" } ]
	Tags []GCPCloudAccountTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date when entity was last updated. Date and time format is ISO 8601 and UTC.
	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type GCPCloudAccountParameters struct {

	// GCP Client email.
	// GCP Client email.
	// +kubebuilder:validation:Optional
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of GCP cloud account.
	// The name of this resource instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// GCP Private key ID.
	// GCP Private key ID.
	// +kubebuilder:validation:Optional
	PrivateKeyID *string `json:"privateKeyId,omitempty" tf:"private_key_id,omitempty"`

	// GCP Private key.
	// GCP Private key.
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef v1.SecretKeySelector `json:"privateKeySecretRef" tf:"-"`

	// GCP Project ID.
	// GCP Project ID.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of region names enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +kubebuilder:validation:Optional
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// Set of tag keys and values to apply to the cloud account. Example: [ { "key" : "vmware", "value": "provider" } ]
	// +kubebuilder:validation:Optional
	Tags []GCPCloudAccountTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GCPCloudAccountTagsInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type GCPCloudAccountTagsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type GCPCloudAccountTagsParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// GCPCloudAccountSpec defines the desired state of GCPCloudAccount
type GCPCloudAccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GCPCloudAccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GCPCloudAccountInitParameters `json:"initProvider,omitempty"`
}

// GCPCloudAccountStatus defines the observed state of GCPCloudAccount.
type GCPCloudAccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GCPCloudAccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GCPCloudAccount is the Schema for the GCPCloudAccounts API. Creates a vra_cloud_account_gcp resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type GCPCloudAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientEmail) || (has(self.initProvider) && has(self.initProvider.clientEmail))",message="spec.forProvider.clientEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privateKeySecretRef)",message="spec.forProvider.privateKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privateKeyId) || (has(self.initProvider) && has(self.initProvider.privateKeyId))",message="spec.forProvider.privateKeyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regions) || (has(self.initProvider) && has(self.initProvider.regions))",message="spec.forProvider.regions is a required parameter"
	Spec   GCPCloudAccountSpec   `json:"spec"`
	Status GCPCloudAccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GCPCloudAccountList contains a list of GCPCloudAccounts
type GCPCloudAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GCPCloudAccount `json:"items"`
}

// Repository type metadata.
var (
	GCPCloudAccount_Kind             = "GCPCloudAccount"
	GCPCloudAccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GCPCloudAccount_Kind}.String()
	GCPCloudAccount_KindAPIVersion   = GCPCloudAccount_Kind + "." + CRDGroupVersion.String()
	GCPCloudAccount_GroupVersionKind = CRDGroupVersion.WithKind(GCPCloudAccount_Kind)
)

func init() {
	SchemeBuilder.Register(&GCPCloudAccount{}, &GCPCloudAccountList{})
}
