// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AWSCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BlockDevice) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BlockDeviceSnapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Blueprint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BlueprintVersion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogItemEntitlement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogItemVMImage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogItemVROWorkflow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogSourceBlueprint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogSourceEntitlement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContentSharingPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContentSource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Deployment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FabricCompute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FabricDatastoreVSphere) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FabricNetworkVSphere) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FlavorProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GCPCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ImageProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Integration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Machine) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Network) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkIPRange) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NSXTCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NSXVCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyApproval) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyDay2Action) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyIaaSResource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyLease) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageProfileAWS) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageProfileAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageProfileVSphere) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VMCCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VsphereCloudAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Zone) Hub() {}
