// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyLeaseInitParameters struct {

	// The policy criteria.
	// The policy criteria.
	Criteria []map[string]*string `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// A human-friendly description for the policy instance.
	// A human-friendly description for the policy instance.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of enforcement for the policy. Supported values: HARD, SOFT.
	// The type of enforcement for the policy.
	EnforcementType *string `json:"enforcementType,omitempty" tf:"enforcement_type,omitempty"`

	// The duration in days that an expired object should be held before it is deleted. Valid range: 0 - 127.
	// The duration in days that an expired object should be held before it is deleted.
	LeaseGrace *float64 `json:"leaseGrace,omitempty" tf:"lease_grace,omitempty"`

	// The maximum duration in days between creation (or renewal) and expiration. Valid range: 1 - 32767.
	// The maximum duration in days between creation (or renewal) and expiration.
	LeaseTermMax *float64 `json:"leaseTermMax,omitempty" tf:"lease_term_max,omitempty"`

	// The maximum duration in days between creation and expiration. Unaffected by renewal. Valid range: 1 - 32767.
	// The maximum duration in days between creation and expiration. Unaffected by renewal.
	LeaseTotalTermMax *float64 `json:"leaseTotalTermMax,omitempty" tf:"lease_total_term_max,omitempty"`

	// A human-friendly name used as an identifier for the policy instance.
	// A human-friendly name used as an identifier for the policy instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project based criteria. Updating this argument triggers a recreation of the resource. It cannot be specified when project_id is set.
	// The project based criteria.
	ProjectCriteria []map[string]*string `json:"projectCriteria,omitempty" tf:"project_criteria,omitempty"`

	// The id of the project this entity belongs to. Updating this argument triggers a recreation of the resource.
	// The id of the project this entity belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type PolicyLeaseObservation struct {

	// Date when the entity was created. The date is in ISO 8601 and UTC.
	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The user the entity was created by.
	// The user the entity was created by.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// The policy criteria.
	// The policy criteria.
	Criteria []map[string]*string `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// A human-friendly description for the policy instance.
	// A human-friendly description for the policy instance.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of enforcement for the policy. Supported values: HARD, SOFT.
	// The type of enforcement for the policy.
	EnforcementType *string `json:"enforcementType,omitempty" tf:"enforcement_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	LastUpdatedAt *string `json:"lastUpdatedAt,omitempty" tf:"last_updated_at,omitempty"`

	// The user the entity was last updated by.
	// The user the entity was last updated by.
	LastUpdatedBy *string `json:"lastUpdatedBy,omitempty" tf:"last_updated_by,omitempty"`

	// The duration in days that an expired object should be held before it is deleted. Valid range: 0 - 127.
	// The duration in days that an expired object should be held before it is deleted.
	LeaseGrace *float64 `json:"leaseGrace,omitempty" tf:"lease_grace,omitempty"`

	// The maximum duration in days between creation (or renewal) and expiration. Valid range: 1 - 32767.
	// The maximum duration in days between creation (or renewal) and expiration.
	LeaseTermMax *float64 `json:"leaseTermMax,omitempty" tf:"lease_term_max,omitempty"`

	// The maximum duration in days between creation and expiration. Unaffected by renewal. Valid range: 1 - 32767.
	// The maximum duration in days between creation and expiration. Unaffected by renewal.
	LeaseTotalTermMax *float64 `json:"leaseTotalTermMax,omitempty" tf:"lease_total_term_max,omitempty"`

	// A human-friendly name used as an identifier for the policy instance.
	// A human-friendly name used as an identifier for the policy instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the organization this entity belongs to.
	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// The project based criteria. Updating this argument triggers a recreation of the resource. It cannot be specified when project_id is set.
	// The project based criteria.
	ProjectCriteria []map[string]*string `json:"projectCriteria,omitempty" tf:"project_criteria,omitempty"`

	// The id of the project this entity belongs to. Updating this argument triggers a recreation of the resource.
	// The id of the project this entity belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type PolicyLeaseParameters struct {

	// The policy criteria.
	// The policy criteria.
	// +kubebuilder:validation:Optional
	Criteria []map[string]*string `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// A human-friendly description for the policy instance.
	// A human-friendly description for the policy instance.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of enforcement for the policy. Supported values: HARD, SOFT.
	// The type of enforcement for the policy.
	// +kubebuilder:validation:Optional
	EnforcementType *string `json:"enforcementType,omitempty" tf:"enforcement_type,omitempty"`

	// The duration in days that an expired object should be held before it is deleted. Valid range: 0 - 127.
	// The duration in days that an expired object should be held before it is deleted.
	// +kubebuilder:validation:Optional
	LeaseGrace *float64 `json:"leaseGrace,omitempty" tf:"lease_grace,omitempty"`

	// The maximum duration in days between creation (or renewal) and expiration. Valid range: 1 - 32767.
	// The maximum duration in days between creation (or renewal) and expiration.
	// +kubebuilder:validation:Optional
	LeaseTermMax *float64 `json:"leaseTermMax,omitempty" tf:"lease_term_max,omitempty"`

	// The maximum duration in days between creation and expiration. Unaffected by renewal. Valid range: 1 - 32767.
	// The maximum duration in days between creation and expiration. Unaffected by renewal.
	// +kubebuilder:validation:Optional
	LeaseTotalTermMax *float64 `json:"leaseTotalTermMax,omitempty" tf:"lease_total_term_max,omitempty"`

	// A human-friendly name used as an identifier for the policy instance.
	// A human-friendly name used as an identifier for the policy instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project based criteria. Updating this argument triggers a recreation of the resource. It cannot be specified when project_id is set.
	// The project based criteria.
	// +kubebuilder:validation:Optional
	ProjectCriteria []map[string]*string `json:"projectCriteria,omitempty" tf:"project_criteria,omitempty"`

	// The id of the project this entity belongs to. Updating this argument triggers a recreation of the resource.
	// The id of the project this entity belongs to.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

// PolicyLeaseSpec defines the desired state of PolicyLease
type PolicyLeaseSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyLeaseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyLeaseInitParameters `json:"initProvider,omitempty"`
}

// PolicyLeaseStatus defines the observed state of PolicyLease.
type PolicyLeaseStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyLeaseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyLease is the Schema for the PolicyLeases API. A resource for Lease policies.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type PolicyLease struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enforcementType) || (has(self.initProvider) && has(self.initProvider.enforcementType))",message="spec.forProvider.enforcementType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.leaseTermMax) || (has(self.initProvider) && has(self.initProvider.leaseTermMax))",message="spec.forProvider.leaseTermMax is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.leaseTotalTermMax) || (has(self.initProvider) && has(self.initProvider.leaseTotalTermMax))",message="spec.forProvider.leaseTotalTermMax is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PolicyLeaseSpec   `json:"spec"`
	Status PolicyLeaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyLeaseList contains a list of PolicyLeases
type PolicyLeaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyLease `json:"items"`
}

// Repository type metadata.
var (
	PolicyLease_Kind             = "PolicyLease"
	PolicyLease_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyLease_Kind}.String()
	PolicyLease_KindAPIVersion   = PolicyLease_Kind + "." + CRDGroupVersion.String()
	PolicyLease_GroupVersionKind = CRDGroupVersion.WithKind(PolicyLease_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyLease{}, &PolicyLeaseList{})
}
